### ISSUE TITLE
cant launch the bat

### ISSUE THREAD

**Issue by kelvinlee1237** [speige/WC3MapDeprotector#15]
![Screenshot 2023-12-20 141011](https://github.com/speige/WC3MapDeprotector/assets/102725916/7cce6831-1dd4-4efe-82e4-313b308dd363)

**Comment by speige** [comment]
You can't run directly from the .zip, you have to extract the files, then run it from the extracted folder.
Please re-open if you're still having issues.

**Comment by ChyngyzAsankulov** [comment]
I have the same issue and ive tried ur recommendation and it still does not open from extracted folder
