### ISSUE TITLE
[Suggestion] Delete old attempts

### ISSUE THREAD

**Issue by kmlkmljkl2** [speige/WC3MapDeprotector#17]
In case the program crashes or needs to be force closed it leaves behind all work files and creates another folder instead.
I'm currently testing with a big map and got GB worth of data real quick. (FOA S3 Rebirth v1.1b.w3x map size 177MB)

Suggestion: Add a checkbox to delete by default.
Can be unchecked if the User wants to keep it.

If this is intended feel free to close this issue.

**Comment by speige** [comment]
Thanks for the bug report. I'll get this fixed soon.

**Comment by speige** [comment]
Fixed in 7317b80 will release new version soon
