### ISSUE TITLE
Program not responding (despite still doing *something*), any way to get verbose debug logs?

### ISSUE THREAD

**Issue by andrewjbennett** [speige/WC3MapDeprotector#23]
Disclaimer: I'm running this on Windows 7 in a VM, so maybe that's unsupported? 

 I've run the program on a specific map, it seems to make progress until it reaches a specific point and then "freezes". I have minimal Windows debugging experience (but plenty of experience in Linux) but I can see that it's still doing something, it's pegged at 25% CPU (maybe 100% of a single core?), and it's still creating and exiting threads, but I can't really tell what it's stuck on trying to do.

This shows the currently running threads (I believe):
![Screenshot from 2024-03-02 16-15-56](https://github.com/speige/WC3MapDeprotector/assets/864138/2743edff-e999-433d-9e2c-13b492907033)

This seems to be what the main thread is doing:
![image](https://github.com/speige/WC3MapDeprotector/assets/864138/8cadffdd-9394-4370-a20e-d37bafa46f61)

This is the log from procmon showing it creating and exiting threads:
![Screenshot from 2024-03-02 16-15-17](https://github.com/speige/WC3MapDeprotector/assets/864138/1db1544a-3d48-4524-86b2-d18ad2102389)

This is what the program itself looks like: 
![image](https://github.com/speige/WC3MapDeprotector/assets/864138/37fe4757-cdc6-4f0e-886c-cb279503e51a)

---

My main question: is there a way that I can get any more verbose debugging output, so that I can see what it's stuck on? My guess would be that it's successfully processed up to whatever point, and then the next thing it's trying to do ends up confusing it (e.g. maybe something was done when protecting the map which is even confusing your program?), but I don't really have any way of knowing this.

Another question: how would one build this from source? I assume there's some common windows dotnet whatever development environment that you can use? If you can give me some basic details (e.g. the name of whatever program/etc is used) I can probably work the rest out from there :)

**Comment by andrewjbennett** [comment]
Oh, and another question: given that I can see it is still doing *something*, if I left this running for hours/days would it eventually progress?

I'm mostly just doing this to mess around with things / try it out, so I'm not too fussed about getting this specific map to work (I just wanted to see if there was a way to make it do a better job at where it places the starting players since it's doing a bad job at putting teams together).

**Comment by speige** [comment]
This is the development environment if you want to build from source. It also has a debugger so you can step through the code as its running & see where it's stuck.
https://visualstudio.microsoft.com/vs/community/

**Comment by speige** [comment]
I ran it on my PC & it didn't get stuck. It finished processing ~ 1 minute. My guess is your VM doesn't have enough resources (CPU or RAM). The program does use a lot of RAM, I've seen it freeze before if the PC runs out of RAM, which is common on VMs.

Unfortunately, even though the program finished for me on TerraceField, it still wouldn't open in WorldEdit, so it must have a form of protection that's not supported yet. Once you get the freezing fixed, I'd recommend trying it on other maps.

**Comment by andrewjbennett** [comment]
Ooh, thanks for the super quick response! I'll try building from source and seeing if I can work out where it's stuck. The VM doesn't seem to be lacking in RAM ([screenshot](https://github.com/speige/WC3MapDeprotector/assets/864138/9bbb79a2-518d-407c-a344-e5d3a0cb2cf1)), but WC3MapDeprotector is definitely pegged at 100% of one CPU.

**Comment by speige** [comment]
Strange. Maybe try adding more CPUs to your VM, if possible, to see if it helps.

As far as "verbose logs". The bottom window that says "Debug Log" is extremely verbose already.

It looks like yours got stuck after this line:
```
Extracted File: discovered\ReplaceableTextures\CommandButtonsDisabled\DISBTNThreshingField.blp
```

Here's my log around that same point in time
```
Extracted File: discovered\buildings\human\MilitiaMaintenanceStation\MilitiaMaintenanceStation(NoPeasants).mdx
Extracted File: discovered\ReplaceableTextures\CommandButtonsDisabled\DISBTNThreshingField.blp
Extraction Completed
Extracted from MPQ: (listfile)
Deleting (attributes)...
Deleting (listfile)...
Unknown file count: 0
```

So, if you do step through the source, you'll want to see why "Extraction Completed" never appeared on your debug log, that's probably where it's getting stuck.

It's pretty strange to be honest, I feel like it must be stuck in an infinite loop somewhere, but not sure why it works differently on your PC compared to mine.

**Comment by andrewjbennett** [comment]
I couldn't get Visual Studio to work on my Windows 7 VM, but I managed to get a ["Windows Development Environment"](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) VM running, and I can successfully run your prebuilt one in the Windows 11 VM, and build it myself from source there.

I've managed to make substantial progress with windbg on my Windows 7 VM though (once I managed to get a new enough version running + worked out that I need to load some extra stuff to make it work with a .NET program).

I think you're right in that it's caught in an infinite loop.

It's running this part of the code over and over: ![Screenshot from 2024-03-03 14-51-43](https://github.com/speige/WC3MapDeprotector/assets/864138/dbf178b2-e562-420f-b16a-e9ae8f258733)

I added some debug prints to narrow it down further:

![image](https://github.com/speige/WC3MapDeprotector/assets/864138/0defd176-d337-488b-849f-7ea20f261f13)

![image](https://github.com/speige/WC3MapDeprotector/assets/864138/7a2e37b3-749f-4c3c-84d2-17073100b41d)

---

I'm not sure if it's worth me continuing to try to debug, given that I've got a way that I can run it (the W11 VM), but let me know if there's anything more you'd like me to try.

**Comment by andrewjbennett** [comment]
BTW, this is the log output, the bit at the end just repeats infinitely: [wc3-log.txt](https://github.com/speige/WC3MapDeprotector/files/14471755/wc3-log.txt). 

FWIW, this file is the only time that `_fileIndexToMd5` does already contain the file index. According to the logs it has indeed extracted that file before it then tries to extract it again, so maybe something isn't properly handling reaching the end of the MPQArchive file or something? (as in, something like, after reading that last file that it gets stuck on from the MPQArchive file, the file pointer isn't at the end of the file properly so it goes back and tries to read the last file again? idk, just wildly speculating)

Also, I've tried running it on several different maps now, including official Blizzard Frozen Throne ones (which surely aren't protected / doing anything sneaky) and it gets into that same infinite loop for every map I've tried, so it's not just that that one map has some fancy protection stuff which ends up confusing your program.

**Comment by speige** [comment]
Since the app is working correctly on your other VM, it's probably not necessary to debug further. If more people run into the same issue I'll try to fix the bug.

Thanks for the log & WinDBG, those will be helpful if I research this in the future.

**Comment by speige** [comment]
Closing  this since I haven't heard any other complaints & it's working on your 2nd PC.
