### ISSUE TITLE
Implement - Discovered Names Database

### ISSUE THREAD

**Issue by Mottemo** [speige/WC3MapDeprotector#27]
It would be great to implement a database in which the names of the files found can be stored.
Perhaps the hash value of the map file could also be stored there in order to be able to search in the database.

This would perhaps make it easier for many users. 
For example, if someone has found the names by brute force, others no longer have to do this if they want to restore the same map.

**Comment by speige** [comment]
Great idea.

I believe this is a duplicate issue. So I'm closing it.
https://github.com/speige/WC3MapDeprotector/issues/2


Although this is a useful feature it's low priority for me so it may not be completed for a long time. Feel free to code it yourself & submit a pull request if you want.
