### ISSUE TITLE
After deprotected still getting this error

### ISSUE THREAD

**Issue by Amarboldaev** [speige/WC3MapDeprotector#29]
How can i fix ? 
![image](https://github.com/speige/WC3MapDeprotector/assets/49066620/d9c53602-8736-4d1f-a941-3d069384d080)

**Comment by speige** [comment]
Please give me the full name of the map file you're trying to deprotect.

**Comment by Amarboldaev** [comment]
Thanks for your reply, the name is vampirisim speed v4.0.3

**Comment by speige** [comment]
I downloaded from this link https://www.epicwar.com/maps/307430/
Is this correct? If not, please send me a link.

When I test on my machine, I don't see this error. Can you give me more details on how to reproduce? For example, are you deprotecting triggers as text or gui? Is this when you first open the map in worldedit? Or does it open fine, but crash when clicking a specific button?

**Comment by Amarboldaev** [comment]
Yes it is correct map, 

First when deprotect with your tool "WC3MapDeprotector" and it created Vampirism SPEED X v4.03_deprotected.w3x 
after that I opened worldedit.exe and try to opens the map but it gives this error.

**Comment by Amarboldaev** [comment]
my WC3MapDeprotector version is 1.16

**Comment by Amarboldaev** [comment]
Yes it is the correct map. 

I opens the tool "WC3MapDeprotector 1.2.0.0" 
![image](https://github.com/speige/WC3MapDeprotector/assets/49066620/717ba7dc-0f72-4d44-817d-b89a71b84e4b)

and clicked the rebuild.
![image](https://github.com/speige/WC3MapDeprotector/assets/49066620/3cf63c05-9d4d-4519-84da-da4ece3ad8c7)

and this popup shows. 
![image](https://github.com/speige/WC3MapDeprotector/assets/49066620/08d1f363-b1b9-4bae-a9da-c162352d3305)

after the new map named *_deprotected.w3x "D:\Game\Warcraft III\Maps\Deprotect test\deprotected\Vampirism SPEED X v4.03_deprotected.w3x" i try to open with worldedit.exe 

then the error shows.

**Comment by Amarboldaev** [comment]
also i try open with "mpqeditor" the *_deprotected map is opened.  

![image](https://github.com/speige/WC3MapDeprotector/assets/49066620/5e0679ca-22a0-4926-afc6-3b28d7d87cb0)

**Comment by speige** [comment]
That's very strange, because it's working fine for me.
I wonder if you're using a different version of warcraft 3 than me? I'm on the latest version of reforged.

![image](https://github.com/speige/WC3MapDeprotector/assets/2002030/3f59df02-04e4-40a8-99e1-83f996215c42)

**Comment by Amarboldaev** [comment]
Aah i see, my version of warcraft is 1.26 😅😅 thanks for your kind support.. any ways do you have linkedin?

**Comment by speige** [comment]
https://www.linkedin.com/in/devin-garner/

**Comment by speige** [comment]
You could try this tool to downgrade the deprotected reforged map down to older versions of warcraft.
https://www.hiveworkshop.com/threads/map-adapter.326456/
