### ISSUE TITLE
Compatibility for 1.26a

### ISSUE THREAD

**Issue by styla01** [speige/WC3MapDeprotector#30]
Hello,
I followed with interest this topic because I have the same problem, I use only version 1.26.a: https://github.com/speige/WC3MapDeprotector/issues/29

My big request is if you can make a patch for 1.26a, because many of us stayed on old school w3. Or is there a way to convert from Reforge to 1.26a? In my case it is a map from 2012-2014, made for 1.26a and does not open in Reforged.

Please help

**Comment by speige** [comment]
You could try this tool to downgrade the deprotected reforged map down to older versions of warcraft.
https://www.hiveworkshop.com/threads/map-adapter.326456/

**Comment by styla01** [comment]
Thank you for your reply.
I wanted to try but unfortunately in the deprotected map there are not all the necessary files: https://github.com/Drake53/War3App/blob/master/src/War3App.MapAdapter/PathConstants.cs
My opinion is that using this application to bring the map back to 1.26a may cause errors and complicate things. Best and clean way, as you said is to save it directly from WC3MapDeprotector.

**Comment by speige** [comment]
Which specific files do you think are missing?
In the PathConstants.cs file from the URL you referenced, not all of those files are "required", some of them are optional.

**Comment by speige** [comment]
I've given this a lot of thought and decided I don't want to modify my tool to support old versions. I've added an explanation in the app that the officially recommended way is to deprotect as reforged and then downgrade using the "Map Adapter" tool by Drake53 on HiveWorkshop at https://www.hiveworkshop.com/threads/map-adapter.326456/
