### ISSUE TITLE
Deprotection of "CHS - Custom Hero Sufvival"

### ISSUE THREAD

**Issue by Mottemo** [speige/WC3MapDeprotector#33]
I try to deptrotect the newest Version of the CHS Map. It can be found here:
Customherosurvival.com

The deptrotection seems to work fine at the first moment (it doenst find 36 files but that is not a problem).

But when i play the deptrotected map all heroes are replaced with i think default wc3 heroes.
Why did it happen? I havent opened it in the world editor. Just tried to play it.

Normaly when you start the map you can choose from many different heroes.

My intention is to just edit the jason script file to increase the timer between the fight round so that you have more time to read the abilitys and to shop items.

**Comment by speige** [comment]
Please give me the epicwar URL

**Comment by Mottemo** [comment]
I cant find it on epicwar. I tried to upload it there but i get an error message: Map is missing 'war3map.mmp'
[CHS_v2.3.6.zip](https://github.com/user-attachments/files/15508784/CHS_v2.3.6.zip)
So i attached the Map in this post.

**Comment by speige** [comment]
Thanks for the link. I'll do some research when I have time & try to improve the deprotector. Unfortunately, it may not be fixed for a long time as I don't have a lot of free time right now.

I've seen a similar issue before. Protection converts war3map.* files (containing object editor data) into *.slk files. Deprotection has to convert from *.slk back to war3map.* files. I think my tool has a bug in doing this conversion.

There is an alternate tool for reversing *.slk files, you can download it here: https://github.com/sumneko/w3x2lni
This isn't a full deprotector, so you'd have to take the resulting files & copy them into the deprotected .w3x file
Not sure if that'll fix it, but it's worth a try, if you want to tinker.


If you just want to edit war3map.j, you don't need any deprotection at all. Just use MPQEditor with the protected map.
http://www.zezula.net/en/mpq/download.html

I have a tutorial video here explaining how to edit war3map.j directly:
https://youtu.be/Og1bGnSEoy8

**Comment by speige** [comment]
I've just released a new version of my tool, please try it out and see if it works better for you.
I can quick general advice over discord, my username is speige
I generally don't have time for custom requests, but if you want me to actually fix the problems for you, I can do it for a fee. My donation page is https://github.com/sponsors/speige
