### ISSUE TITLE
Option to leave files untouched

### ISSUE THREAD

**Issue by Mottemo** [speige/WC3MapDeprotector#34]
Hi,
i often want to deprotect Maps to just be able to edit the jasson script file. So i do not need the ability to open it in the Map Editor.

I think you optimize many files to be able to open the map in the map editor, right?
But i think these procedures could break the map.

Could you give me the option to just edit the script file?

**Comment by speige** [comment]
If you just want to edit war3map.j, you don't need any deprotection at all. Just use MPQEditor.

I have a tutorial video here:
https://youtu.be/Og1bGnSEoy8
